name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: '3.8'
            django: '>=3.0,<3.1'
          - python: '3.9'
            django: '>=3.2,<3.3'
          - python: '3.10'
            django: '>=4.0,<4.1'
          - python: '3.11'
            django: '>=4.1,<4.2'
          - python: '3.11'
            django: '>=4.2,<4.3'
          - python: '3.12'
            django: '>=5.0,<5.1'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "Django${{ matrix.django }}"
          pip install -e .[testing]
      - name: Test
        run: ./runtests.py
